package Game.Core;

public enum GameState {

	MAIN_MENU,
	GAME_RUNTIME_SINGLEPLAYER,
	GAME_RUNTIME_MULTIPLAYER,
	NEW_SINGLEPLAYER,
	NEW_MULTIPLAYER_HOST,
	NEW_MULTIPLAYER_CLIENT,
	LOAD_SAVE,
	LOAD_MULTIPLAYER_HOST,
	LOAD_MULTIPLAYER_CLIENT,
	BUSY,
	;
	
}
